# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NextJS Build as Export

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Verify the Output Folder
        run: ls -l out

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AlphaApp Build Package
          path: out

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to netlify
        run: |
          netlify deploy --prod \
            --dir=out \
            --site ${( secrets.NELIFY_SITE_ID )} \
            --auth ${( secrets.NELIFY_API_TOKEN )}
