# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NextJS Pipeline

on:
  push:
    branches:
      - main

jobs:
  job1: 
    name: My Name is Job1
    runs-on: ubuntu-latest
    steps:
      - name: First step - Job 1
        run: echo "First step in Job 1"

      - name: Create a file - Job 1
        run: echo "Job1 file" > job1.txt


  job2:
    name: My Name is Job2
    runs-on: ubuntu-latest
    steps:
      - name: Create a file - Job 2
        run: echo "Job2 file" > job2.txt

      - name: Verify the File - Job 2
        run: ls -l job2.txt

  job3:
    name: My Name is Job3
    runs-on: ubuntu-latest
    needs: [Job1, Job2]
    steps:
      - name: Verify the File - Job 3
        run: ls -l